# Generated by Django 4.2.24 on 2025-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_created_at_bill_created_by_bill_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=10),
        ),
    ]
