# Generated by Django 4.2.24 on 2025-09-25 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
