# Generated by Django 4.2.24 on 2025-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billitem_created_at_billitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
