# Generated by Django 4.2.24 on 2025-09-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='created_at',
        ),
    ]
