# Generated by Django 4.2.24 on 2025-09-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_bill_created_at_alter_billitem_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
    ]
