# Generated by Django 4.2.24 on 2025-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_bill_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
